#!/bin/bash
#
# Description.
#
if [ -z "$1" ]; then
  echo "Usage: $0 palavra [palavra ...]"
  exit 1
fi

title="dictsh"

while (( $# > 0 ))
do

  word="$1"
# word=$(zenity --entry --text="diciosh: " --title="Word Input")

  curl -sX GET \
  -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" \
  -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
  -H "Accept-Language: en-US,en;q=0.5" \
  -H "Upgrade-Insecure-Requests: 1" \
  -H "Sec-Fetch-Dest: document" \
  -H "Sec-Fetch-Mode: navigate" \
  -H "Sec-Fetch-Site: same-origin" \
  -H "Sec-Fetch-User: ?1" \
  -H "Referer: https://www.sinonimos.com.br/" \
  https://www.sinonimos.com.br/busca.php?q=$word > tmp

  json_data=`cat tmp | tr '\n' ' ' | sed -e 's/^.*resultados//' | sed -e 's/sidebar.*$//' \
  | sed -e 's/<[^>]*>//g' | grep -Po ': .*<' | sed -e 's/[^a-z]*//' \
  | sed -e 's/  //g' | sed -e 's/S[^:]*//g' \
  | sed -e 's/, /", "/g' | sed -e 's/^/"/' | sed -e 's/ : /": ["/g' \
  | sed -e 's/\([a-z]\) \([a-z]\)/\1", "\2/g' \
  | sed -e 's/, \("[a-z]\+":\)/], \1/g' \
  | sed -e 's/^/{ /' | sed -e 's/ <$/"] }/'`

  keys=`echo "$json_data" | jq -r 'keys[]'`
  readarray -t key_array <<< "$keys"

  echo "[ $word ]"
  for key in "${key_array[@]}"; do
    value=$(echo "$json_data" | jq -r ".${key}")
    if [[ $(echo "$value" | jq -r 'type') == "array" ]]; then
      echo -en "- $key:\n  "
      echo "$value" | jq -r '.[]' | while read element; do
        echo -n "$element "
      done
      echo
    else
      echo "ERROR ($word)"
      cat tmp
    fi
  done

shift
done
rm tmp
